### ISSUE TITLE
CI bug during JDK 21 update

### ISSUE THREAD

**Issue by dan-du-car** [usdot-jpo-ode/jpo-sdw-depositor#31]
Upgrade JDK from 17 to 21. The CI encounters issues with mvn compile: https://github.com/usdot-jpo-ode/jpo-sdw-depositor/actions/runs/7718201231/job/21038948614

**Comment by drewjj** [comment]
Updating to openjdk 21 doesn't fix this

**Comment by dan-du-car** [comment]
> Updating to openjdk 21 doesn't fix this

We might have two different JAVA versions setup during the CI action workflow. I removed the stepactions/setup-java@v4. That seems fix this issue.

**Comment by dan-du-car** [comment]
Issue closed for now as the develop branch CI build successfully after merging this PR: https://github.com/usdot-jpo-ode/jpo-sdw-depositor/pull/34
